services:
  # sua aplicação Spring Boot
  app:
    build: .
    container_name: sistema_venda_ingressos_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/venda_ingressos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - rede_ingressos

  # banco de dados PostgreSQL
  db:
    image: postgres:16
    container_name: sistema_venda_ingressos_db
    environment:
      POSTGRES_DB: venda_ingressos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    networks:
      - rede_ingressos

volumes:
  dados_postgres:

networks:
  rede_ingressos:
